#!/bin/bash

work() {
    if [ -d "$1" -o -z "$1" ] ; then
        $DIR_EXEC "${1:-.}"
    else
        $FILE_EXEC "$1"
    fi
}

case "$(basename "$0")" in
"lscat")
    DIR_EXEC='ls --color=auto'
    FILE_EXEC='cat'
    ;;
"llcat")
    DIR_EXEC='ls -l --color=auto'
    FILE_EXEC='cat'
    ;;
"lsvim")
    DIR_EXEC='ls --color=auto'
    FILE_EXEC='vim'
    ;;
"llvim")
    DIR_EXEC='ls -l --color=auto'
    FILE_EXEC='vim'
    ;;
"lsvimr")
    DIR_EXEC='ls --color=auto'
    FILE_EXEC='vim -R'
    ;;
"llvimr")
    DIR_EXEC='ls -l --color=auto'
    FILE_EXEC='vim -R'
    ;;
*)
    # My favourite is this combo:
    DIR_EXEC='ls -l --color=auto'
    FILE_EXEC='vim'
esac

if [ $# -gt 1 ] ; then
    for i in "$@" ; do
        echo $i:
        work "$i"
        echo
    done
else
    work "$1"
fi
